name: Deploy to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Add Azure VM to known hosts
        run: |
          ssh-keyscan -H 4.221.184.222 >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM
        run: |
          rsync -avz --delete \
            --exclude='.env' \
            --exclude=node_modules \
            --exclude=.next \
            --exclude=.git \
            ./ root@4.221.184.222:/var/www/fiesta-frenzy

      - name: Run build and restart PM2
        run: |
          ssh root@4.221.184.222 "
            cd /var/www/fiesta-frenzy &&
            npm install &&
            npm run build &&
            pm2 restart fiesta-frenzy &&
            sudo systemctl restart apache2
          "
